# Generated by Django 3.2.5 on 2021-07-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
